### ISSUE TITLE
Nothing after construct tagging interface

### ISSUE THREAD

**Issue by lucyfriedland** [ASL-LEX/SignLab#87]
**Describe the bug**

I added two tag field ASL-LEX items, "hot" F_02_093 and "cold" C_02_068 . Just to as a test to see what happens next, I pressed "next" and the following page has nothing to see. In order to see what happens after that, I pressed "submit" but nothing happened. I would assume that pressing submit would then create the test or save it somehow, but it wouldn't do anything. "submit" seemed to be like a false button. I clicked "study control," thinking that something may have been saved there, but it just erased the progress I made. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lucyfriedland** [comment]
<img width="1680" alt="Screenshot 2023-04-06 at 1 06 27 PM" src="https://user-images.githubusercontent.com/126619586/230447483-2b878e16-0a79-4b3c-8c7d-936b08191996.png">

**Comment by cbolles** [comment]
@lucyfriedland thanks for filing the bug report and attaching the screenshot. It seems to be two different issues.

First seeing nothing on that page happens when a project doesn't have access to a dataset. Normally that would be where you can enable different entries for tagging. For that the fix I should add in would be having some text to make it clear why it looks like that.

For the submission button not doing anything, I'm going to have to look into that more. Would you be able to capture a screenshot with the console pulled up? If you aren't familiar with opening the console you can check out [this link](https://balsamiq.com/support/faqs/browserconsole/#:~:text=To%20open%20the%20developer%20console,(on%20Windows%2FLinux).)

**Comment by cbolles** [comment]
Found the issue with the study creation. Should be fixed soon, I'll let you know when it is resolved in production.

**Comment by cbolles** [comment]
@lucyfriedland this should be fixed now where you will see a message if the project does not have access to any datasets and project admin's have the ability to make studies.

You may run into a different issue where project admin's cannot delete studies which I am in the process of resolving.
